name: PHP QA
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    uses: opentelemetry-php/gh-workflows/.github/workflows/php.yml@main
    with:
      strategy:
        fail-fast: false
        matrix:
          php-version: ['7.4', '8.0', '8.1']
          os: [ubuntu-latest]

