name: PHP QA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    uses: opentelemetry-php/gh-workflows/.github/workflows/php.yml@main
    with:
      matrix_extension: '["ast, json"]'
